### ISSUE TITLE
在测试实验2时，发现了一个词法问题

### ISSUE THREAD

**Issue by Ashside** [CrystalVapor/HITCompilerPrincipleLab#3]
# 尝试修改测试用例`test1.cmm`，产生不合理的词法报错

这是原测试用例
```
int main(){
    int i = 0;
    j = i +<space>1;
}
```

我将其修改为
```
int main(){
    int i = 0;
    j = i +1;
}
```

产生错误信息如下
```
Error type B at line 3: Unexpected Expression
Lexical or syntax error detected, aborted before semantic analyzing.
```

这是不合理的，猜测词法分析器将`+`识别为了整型数的一部分

我的运行步骤
```
./Lab2  testLab2/test1.cmm
```

**Comment by Ashside** [comment]
# 一个可能的思路
不再匹配整型数前的`+`和`-`
> 此处`j=i -1;`也会有同样的问题

但是这样的话，整型数无法声明为负数

**Comment by CrystalVapor** [comment]
你好！
这个问题确实是因为错误地匹配了词前的加号导致的
但问题不止如此：词法程序也会错误地匹配诸如i-1的语句为词法单元串 ID, INT
这是由于在Float和Int的正则词法串中，我们使用了可选的+/-号作为这两种字面值的合法前缀
这符合直觉，但并不能作为一个合法的词法正则表达式使用。
另外，我们的语法分析中有类似 EXP-> MINUS EXP的语法单元，它可以正确地匹配负号的语法
我在提交 98b43e3 中移除了这个可选前缀，现在程序应该可以正常运行了！
感谢你的细心调试！
