### ISSUE TITLE
实验三测试用例extra2的中间代码生成有误

### ISSUE THREAD

**Issue by ErnestThePoet** [CrystalVapor/HITCompilerPrincipleLab#4]
执行`./Lab3 testLab3/extra2.cmm > testLab3/output/extra2.ir`，得到的中间代码的第22行为：
```
t13 := t11 + t12
```
然而变量名`t11`之前并未被定义过，放入IR虚拟机执行时将导致报错

**Comment by ErnestThePoet** [comment]
![image](https://github.com/CrystalVapor/HITCompilerPrincipleLab/assets/53808118/9a711b42-150a-4058-9c11-449685a01130)

**Comment by CrystalVapor** [comment]
你好，感谢回复！
相关问题已经加入日程表，将择日着手修复

**Comment by CrystalVapor** [comment]
你好！
在花费了少量时间后，我定位到了问题所在：
IntercodeGenerator.c, line ~1635( case Exp->Exp Lp Exp Rp)
在以往的代码中，用于生成数组地址的代码被错误地丢弃，这不仅造成了内存泄漏，同时还会导致使用了从未出现过的变量
(v11本身应当存储数组的首地址)
在提交 17103c60 中，该问题已被修复。
感谢您的反馈！
