### ISSUE TITLE
调整项目结构的建议

### ISSUE THREAD

**Issue by ErnestThePoet** [CrystalVapor/HITCompilerPrincipleLab#5]
个人认为项目结构可以做一点小小的改进：
### 移除CMake构建产物
CMake生成的Makefile或ninja文件中包含有编译目录的绝对路径，如果其他同学直接使用`make`进行编译，可能因为找不到文件而引发错误，因此保留CMake的构建产物并没有必要，可以整个忽略`/CmakeBuild`目录
### 将测试脚本和测试用例单独存放
目前测试相关代码放在了CMake输出目录中，在第一条建议的基础上，可以把这部分代码放在单独目录中，这样项目结构也更加清晰

**Comment by CrystalVapor** [comment]
你好，感谢回复！
相关问题已经加入日程表，将择日着手修复

**Comment by CrystalVapor** [comment]
你好！
截止到提交 6c31904 
项目结构已经调整完毕
感谢您的反馈！
